### ISSUE TITLE
About using base32 rather than base85.

### ISSUE THREAD

**Issue by ebubekirtrkr** [kaganisildak/c2tify#1]
Wouldn't it be better to use Base85 instead of using Base32? Because if we use Base85, there will be less production time and fewer songs in playlists.

**Comment by kaganisildak** [comment]
Actually no. The main reason we use base32 is because the character set can be included in the songs. Some characters in base85 (eg /, *,?) may not be present in songs. It may be more logical to search for songs that belong to the 2 or 3 permutations of the base32 character set in order to hold more data in fewer songs.

**Comment by ebubekirtrkr** [comment]
Okay I got it. Thanks for answer.
